services:
  backend:
    build: ./Note_App
    container_name: notes_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./Note_App:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: notes_frontend
    build:
      context: ./Note_App/client
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.4.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Note_App/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: